name: multi_sample_metagenomic_assembly
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - megahit
  - spades
  - cd-hit
  - biopython
  - numpy
  - pandas
  # Optional tools for downstream analysis
  - quast
  - kraken2
  - diamond
  - bowtie2
  - samtools
  - seqtk
  - fastqc
  - bbmap
  - matplotlib
  - seaborn